import 'package:flutter/material.dart';

import 'event_manager_models.dart';

// ─── Pipeline Event Status ────────────────────────────────────────────────────

enum PipelineEventStatus {
  draft('Draft', Color(0xFF757575), Icons.edit_outlined),
  published('Published', Color(0xFF1565C0), Icons.public_rounded),
  registrationOpen('Registration Open', Color(0xFF2E7D32), Icons.app_registration_rounded),
  volunteerAssignment('Volunteer Assignment', Color(0xFF6A1B9A), Icons.assignment_ind_rounded),
  scheduled('Scheduled', Color(0xFFE65100), Icons.event_rounded),
  ongoing('Ongoing', Color(0xFFFF6F00), Icons.play_circle_rounded),
  workSubmissionOpen('Work Submission Open', Color(0xFF00695C), Icons.upload_file_rounded),
  verificationPending('Verification Pending', Color(0xFFF57F17), Icons.pending_actions_rounded),
  adminApprovalPending('Admin Approval Pending', Color(0xFFC62828), Icons.admin_panel_settings_rounded),
  completed('Completed', Color(0xFF4CAF50), Icons.check_circle_rounded),
  impactPublished('Impact Published', Color(0xFF1B5E20), Icons.newspaper_rounded),
  archived('Archived', Color(0xFF9E9E9E), Icons.archive_rounded);

  const PipelineEventStatus(this.label, this.color, this.icon);
  final String label;
  final Color color;
  final IconData icon;

  bool get isActive => this == ongoing || this == workSubmissionOpen || this == verificationPending || this == adminApprovalPending;
  bool get isPreEvent => this == draft || this == published || this == registrationOpen || this == volunteerAssignment || this == scheduled;
  bool get isPostEvent => this == completed || this == impactPublished || this == archived;

  static PipelineEventStatus fromString(String v) => PipelineEventStatus.values.firstWhere(
    (e) => e.name == v || e.label.toLowerCase() == v.toLowerCase(),
    orElse: () => PipelineEventStatus.draft,
  );

  // All 12 stages in order for the pipeline progress timeline
  static const List<PipelineEventStatus> pipeline = [
    draft, published, registrationOpen, volunteerAssignment,
    scheduled, ongoing, workSubmissionOpen, verificationPending,
    adminApprovalPending, completed, impactPublished, archived,
  ];

  int get pipelineIndex => pipeline.indexOf(this);
}

// ─── Pipeline Assignment Status ───────────────────────────────────────────────

enum PipelineAssignmentStatus {
  open('Open', Color(0xFF757575), Icons.circle_outlined),
  applied('Applied', Color(0xFF1565C0), Icons.send_rounded),
  assigned('Assigned', Color(0xFFE65100), Icons.assignment_turned_in_rounded),
  inProgress('In Progress', Color(0xFFFF6F00), Icons.pending_rounded),
  submitted('Submitted', Color(0xFFF57F17), Icons.upload_file_rounded),
  resubmissionRequested('Resubmission Requested', Color(0xFF6A1B9A), Icons.replay_rounded),
  eventManagerVerified('EM Verified', Color(0xFF00695C), Icons.verified_rounded),
  adminApproved('Admin Approved', Color(0xFF2E7D32), Icons.check_circle_rounded),
  certificateGenerated('Certificate Generated', Color(0xFF1565C0), Icons.workspace_premium_rounded),
  completed('Completed', Color(0xFF1B5E20), Icons.task_alt_rounded),
  rejected('Rejected', Color(0xFFC62828), Icons.cancel_rounded);

  const PipelineAssignmentStatus(this.label, this.color, this.icon);
  final String label;
  final Color color;
  final IconData icon;

  bool get needsEmAction => this == submitted || this == resubmissionRequested;
  bool get needsAdminAction => this == eventManagerVerified;
  bool get isTerminal => this == completed || this == rejected;

  static PipelineAssignmentStatus fromString(String v) => PipelineAssignmentStatus.values.firstWhere(
    (e) => e.name == v,
    orElse: () => PipelineAssignmentStatus.open,
  );
}

// ─── Certificate Status ───────────────────────────────────────────────────────

enum PipelineCertificateStatus {
  draft('Draft', Color(0xFF757575)),
  pendingPhysicalSign('Pending Physical Sign', Color(0xFFF57F17)),
  physicallySigned('Physically Signed', Color(0xFF2E7D32)),
  pdfUploaded('PDF Uploaded', Color(0xFF1565C0)),
  issued('Issued', Color(0xFF1B5E20));

  const PipelineCertificateStatus(this.label, this.color);
  final String label;
  final Color color;
}

// ─── Impact Post Draft Status ─────────────────────────────────────────────────

enum ImpactPostDraftStatus {
  autoGenerated('Auto Generated', Color(0xFF757575)),
  emEdited('EM Edited', Color(0xFF6A1B9A)),
  adminApproved('Admin Approved', Color(0xFF2E7D32)),
  published('Published', Color(0xFF1B5E20)),
  archived('Archived', Color(0xFF9E9E9E));

  const ImpactPostDraftStatus(this.label, this.color);
  final String label;
  final Color color;
}

// ─── Event Report Status ──────────────────────────────────────────────────────

enum EventReportStatus {
  generated('Generated', Color(0xFF1565C0)),
  finalised('Finalised', Color(0xFF2E7D32)),
  archived('Archived', Color(0xFF9E9E9E));

  const EventReportStatus(this.label, this.color);
  final String label;
  final Color color;
}

// ─── Donation Proof Status ────────────────────────────────────────────────────

enum DonationProofStatus {
  pending('Pending', Color(0xFFF57F17)),
  emVerified('EM Verified', Color(0xFF00695C)),
  adminApproved('Admin Approved', Color(0xFF2E7D32)),
  rejected('Rejected', Color(0xFFC62828));

  const DonationProofStatus(this.label, this.color);
  final String label;
  final Color color;
}

// ─── Models ───────────────────────────────────────────────────────────────────

class PipelineDonationProof {
  final int id;
  final int assignmentId;
  final double amount;
  final String? donorName;
  final String transactionId;
  final DateTime donationDate;
  final String? proofImageUrl;
  final DonationProofStatus status;
  final double? stipendAmount;
  final String? adminNote;

  const PipelineDonationProof({
    required this.id,
    required this.assignmentId,
    required this.amount,
    this.donorName,
    required this.transactionId,
    required this.donationDate,
    this.proofImageUrl,
    this.status = DonationProofStatus.pending,
    this.stipendAmount,
    this.adminNote,
  });

  PipelineDonationProof copyWith({
    DonationProofStatus? status,
    double? stipendAmount,
    String? adminNote,
  }) => PipelineDonationProof(
    id: id,
    assignmentId: assignmentId,
    amount: amount,
    donorName: donorName,
    transactionId: transactionId,
    donationDate: donationDate,
    proofImageUrl: proofImageUrl,
    status: status ?? this.status,
    stipendAmount: stipendAmount ?? this.stipendAmount,
    adminNote: adminNote ?? this.adminNote,
  );
}

class PipelineWorkSubmission {
  final int id;
  final int assignmentId;
  final String workTitle;
  final String description;
  final double hoursWorked;
  final int peopleReached;
  final List<String> photoUrls;
  final List<PipelineDailyLog> logEntries;
  final PipelineDonationProof? donationProof;
  final String? remarks;
  final DateTime submittedAt;

  const PipelineWorkSubmission({
    required this.id,
    required this.assignmentId,
    required this.workTitle,
    required this.description,
    required this.hoursWorked,
    required this.peopleReached,
    this.photoUrls = const [],
    this.logEntries = const [],
    this.donationProof,
    this.remarks,
    required this.submittedAt,
  });
}

class PipelineAssignment {
  final int id;
  final int activityId;
  final int eventId;
  final String studentName;
  final String studentEmail;
  final String activityTitle;
  final String eventTitle;
  final DateTime dueDate;
  final PipelineAssignmentStatus status;
  final PipelineWorkSubmission? submission;
  final String? instructions;
  final String? reviewerNotes;
  final String? adminNotes;
  final DateTime assignedAt;
  final DateTime? submittedAt;
  final DateTime? verifiedAt;
  final DateTime? approvedAt;
  final PipelineCertificate? certificate;

  const PipelineAssignment({
    required this.id,
    required this.activityId,
    required this.eventId,
    required this.studentName,
    required this.studentEmail,
    required this.activityTitle,
    required this.eventTitle,
    required this.dueDate,
    required this.status,
    this.submission,
    this.instructions,
    this.reviewerNotes,
    this.adminNotes,
    required this.assignedAt,
    this.submittedAt,
    this.verifiedAt,
    this.approvedAt,
    this.certificate,
  });

  PipelineAssignment copyWith({
    PipelineAssignmentStatus? status,
    PipelineWorkSubmission? submission,
    String? reviewerNotes,
    String? adminNotes,
    DateTime? verifiedAt,
    DateTime? approvedAt,
    PipelineCertificate? certificate,
  }) => PipelineAssignment(
    id: id,
    activityId: activityId,
    eventId: eventId,
    studentName: studentName,
    studentEmail: studentEmail,
    activityTitle: activityTitle,
    eventTitle: eventTitle,
    dueDate: dueDate,
    status: status ?? this.status,
    submission: submission ?? this.submission,
    instructions: instructions,
    reviewerNotes: reviewerNotes ?? this.reviewerNotes,
    adminNotes: adminNotes ?? this.adminNotes,
    assignedAt: assignedAt,
    submittedAt: submittedAt,
    verifiedAt: verifiedAt ?? this.verifiedAt,
    approvedAt: approvedAt ?? this.approvedAt,
    certificate: certificate ?? this.certificate,
  );

  String get initials {
    final parts = studentName.trim().split(' ');
    if (parts.length >= 2) return '${parts[0][0]}${parts[1][0]}'.toUpperCase();
    return studentName.isNotEmpty ? studentName[0].toUpperCase() : '?';
  }
}

class PipelineActivity {
  final int id;
  final int eventId;
  final String title;
  final ActivityRole role;
  final String? description;
  final int maxStudents;
  final bool requiresDonationProof;
  final bool hasCertificate;
  final List<PipelineAssignment> assignments;

  const PipelineActivity({
    required this.id,
    required this.eventId,
    required this.title,
    required this.role,
    this.description,
    required this.maxStudents,
    this.requiresDonationProof = false,
    this.hasCertificate = true,
    this.assignments = const [],
  });

  int get assignedCount => assignments.length;
  bool get isFull => assignedCount >= maxStudents;
  int get slotsLeft => maxStudents - assignedCount;
  int get pendingSubmissions => assignments.where((a) => a.status == PipelineAssignmentStatus.submitted).length;
  int get verifiedCount => assignments.where((a) => a.status == PipelineAssignmentStatus.eventManagerVerified || a.status == PipelineAssignmentStatus.adminApproved || a.status == PipelineAssignmentStatus.certificateGenerated || a.status == PipelineAssignmentStatus.completed).length;

  PipelineActivity copyWith({List<PipelineAssignment>? assignments}) => PipelineActivity(
    id: id,
    eventId: eventId,
    title: title,
    role: role,
    description: description,
    maxStudents: maxStudents,
    requiresDonationProof: requiresDonationProof,
    hasCertificate: hasCertificate,
    assignments: assignments ?? this.assignments,
  );
}

class PipelineEvent {
  final int id;
  final String title;
  final EventCategory category;
  final PipelineEventStatus status;
  final DateTime date;
  final DateTime? endDate;
  final String location;
  final bool isOnline;
  final String? partnerSchool;
  final String description;
  final String? bannerImageUrl;
  final int maxVolunteers;
  final String assignedEventManagerName;
  final String? assignedCounsellorName;
  final bool certificateEligible;
  final bool donationEligible;
  final bool stipendEligible;
  final double? stipendAmount;
  final String? expectedWork;
  final String? proofRequired;
  final bool reportRequired;
  final bool impactPostEligible;
  final List<PipelineActivity> activities;
  final DateTime createdAt;
  final ImpactPostDraft? impactDraft;
  final EventReport? report;

  const PipelineEvent({
    required this.id,
    required this.title,
    required this.category,
    required this.status,
    required this.date,
    this.endDate,
    required this.location,
    this.isOnline = false,
    this.partnerSchool,
    required this.description,
    this.bannerImageUrl,
    required this.maxVolunteers,
    required this.assignedEventManagerName,
    this.assignedCounsellorName,
    this.certificateEligible = true,
    this.donationEligible = false,
    this.stipendEligible = false,
    this.stipendAmount,
    this.expectedWork,
    this.proofRequired,
    this.reportRequired = true,
    this.impactPostEligible = true,
    this.activities = const [],
    required this.createdAt,
    this.impactDraft,
    this.report,
  });

  int get totalAssigned => activities.fold(0, (sum, a) => sum + a.assignedCount);
  int get totalSubmitted => activities.fold(0, (sum, a) => sum + a.assignments.where((s) => s.status != PipelineAssignmentStatus.open && s.status != PipelineAssignmentStatus.assigned && s.status != PipelineAssignmentStatus.inProgress).length);
  int get totalApproved => activities.fold(0, (sum, a) => sum + a.assignments.where((s) => s.status == PipelineAssignmentStatus.adminApproved || s.status == PipelineAssignmentStatus.certificateGenerated || s.status == PipelineAssignmentStatus.completed).length);
  int get pendingSubmissions => activities.fold(0, (sum, a) => sum + a.pendingSubmissions);
  int get totalPeopleReached => activities.fold(0, (sum, a) => sum + a.assignments.fold(0, (s2, asgn) => s2 + (asgn.submission?.peopleReached ?? 0)));
  double get totalDonationCollected => activities.fold(0.0, (sum, a) => sum + a.assignments.fold(0.0, (s2, asgn) => s2 + (asgn.submission?.donationProof?.amount ?? 0.0)));
  int get certificatesGenerated => activities.fold(0, (sum, a) => sum + a.assignments.where((s) => s.certificate != null).length);
  bool get hasImpactDraft => impactDraft != null;
  bool get hasReport => report != null;

  List<PipelineAssignment> get allAssignments => activities.expand((a) => a.assignments).toList();
  List<PipelineAssignment> get pendingEmReview => allAssignments.where((a) => a.status == PipelineAssignmentStatus.submitted).toList();

  bool get isToday {
    final now = DateTime.now();
    return date.year == now.year && date.month == now.month && date.day == now.day;
  }

  bool get isUpcoming => date.isAfter(DateTime.now());

  PipelineEvent copyWith({
    PipelineEventStatus? status,
    List<PipelineActivity>? activities,
    ImpactPostDraft? impactDraft,
    EventReport? report,
  }) => PipelineEvent(
    id: id,
    title: title,
    category: category,
    status: status ?? this.status,
    date: date,
    endDate: endDate,
    location: location,
    isOnline: isOnline,
    partnerSchool: partnerSchool,
    description: description,
    bannerImageUrl: bannerImageUrl,
    maxVolunteers: maxVolunteers,
    assignedEventManagerName: assignedEventManagerName,
    assignedCounsellorName: assignedCounsellorName,
    certificateEligible: certificateEligible,
    donationEligible: donationEligible,
    stipendEligible: stipendEligible,
    stipendAmount: stipendAmount,
    expectedWork: expectedWork,
    proofRequired: proofRequired,
    reportRequired: reportRequired,
    impactPostEligible: impactPostEligible,
    activities: activities ?? this.activities,
    createdAt: createdAt,
    impactDraft: impactDraft ?? this.impactDraft,
    report: report ?? this.report,
  );
}

// ─── Certificate ──────────────────────────────────────────────────────────────

class PipelineCertificate {
  final int id;
  final String certificateId;
  final int assignmentId;
  final int eventId;
  final String studentName;
  final String eventName;
  final String activityName;
  final double hoursServed;
  final DateTime issueDate;
  final String? signedByName;
  final String? signedByTitle;
  final bool isPhysicallySigned;
  final String? finalPdfUrl;
  final PipelineCertificateStatus status;

  const PipelineCertificate({
    required this.id,
    required this.certificateId,
    required this.assignmentId,
    required this.eventId,
    required this.studentName,
    required this.eventName,
    required this.activityName,
    required this.hoursServed,
    required this.issueDate,
    this.signedByName,
    this.signedByTitle,
    this.isPhysicallySigned = false,
    this.finalPdfUrl,
    this.status = PipelineCertificateStatus.draft,
  });

  PipelineCertificate copyWith({
    bool? isPhysicallySigned,
    String? finalPdfUrl,
    PipelineCertificateStatus? status,
    String? signedByName,
    String? signedByTitle,
  }) => PipelineCertificate(
    id: id,
    certificateId: certificateId,
    assignmentId: assignmentId,
    eventId: eventId,
    studentName: studentName,
    eventName: eventName,
    activityName: activityName,
    hoursServed: hoursServed,
    issueDate: issueDate,
    signedByName: signedByName ?? this.signedByName,
    signedByTitle: signedByTitle ?? this.signedByTitle,
    isPhysicallySigned: isPhysicallySigned ?? this.isPhysicallySigned,
    finalPdfUrl: finalPdfUrl ?? this.finalPdfUrl,
    status: status ?? this.status,
  );
}

// ─── Impact Post Draft ────────────────────────────────────────────────────────

class ImpactPostDraft {
  final int id;
  final int eventId;
  final String eventName;
  final EventCategory eventCategory;
  final String location;
  final DateTime eventDate;
  final List<String> volunteerNames;
  final int totalVolunteers;
  final int peopleReached;
  final double donationCollected;
  final int certificatesIssued;
  final String? partnerSchool;
  String description;
  String appreciationMessage;
  final List<String> photoUrls;
  final ImpactPostDraftStatus status;
  final bool isAutoGenerated;
  final DateTime createdAt;

  ImpactPostDraft({
    required this.id,
    required this.eventId,
    required this.eventName,
    required this.eventCategory,
    required this.location,
    required this.eventDate,
    required this.volunteerNames,
    required this.totalVolunteers,
    required this.peopleReached,
    required this.donationCollected,
    required this.certificatesIssued,
    this.partnerSchool,
    required this.description,
    required this.appreciationMessage,
    this.photoUrls = const [],
    this.status = ImpactPostDraftStatus.autoGenerated,
    this.isAutoGenerated = true,
    required this.createdAt,
  });

  ImpactPostDraft copyWith({
    String? description,
    String? appreciationMessage,
    ImpactPostDraftStatus? status,
    List<String>? photoUrls,
  }) => ImpactPostDraft(
    id: id,
    eventId: eventId,
    eventName: eventName,
    eventCategory: eventCategory,
    location: location,
    eventDate: eventDate,
    volunteerNames: volunteerNames,
    totalVolunteers: totalVolunteers,
    peopleReached: peopleReached,
    donationCollected: donationCollected,
    certificatesIssued: certificatesIssued,
    partnerSchool: partnerSchool,
    description: description ?? this.description,
    appreciationMessage: appreciationMessage ?? this.appreciationMessage,
    photoUrls: photoUrls ?? this.photoUrls,
    status: status ?? this.status,
    isAutoGenerated: isAutoGenerated,
    createdAt: createdAt,
  );
}

// ─── Event Report ─────────────────────────────────────────────────────────────

class EventReport {
  final int id;
  final int eventId;
  final String eventName;
  final EventCategory category;
  final DateTime eventDate;
  final String location;
  final bool isOnline;
  final String eventManagerName;
  final List<String> volunteerNames;
  final int totalVolunteers;
  final int studentsReached;
  final double donationsCollected;
  final int certificatesIssued;
  final List<String> activityTitles;
  final String? partnerDetails;
  final String? counsellorDetails;
  final String? schoolFeedback;
  final String outcomes;
  final List<String> photoUrls;
  final EventReportStatus status;
  final DateTime generatedAt;

  const EventReport({
    required this.id,
    required this.eventId,
    required this.eventName,
    required this.category,
    required this.eventDate,
    required this.location,
    this.isOnline = false,
    required this.eventManagerName,
    required this.volunteerNames,
    required this.totalVolunteers,
    required this.studentsReached,
    required this.donationsCollected,
    required this.certificatesIssued,
    required this.activityTitles,
    this.partnerDetails,
    this.counsellorDetails,
    this.schoolFeedback,
    required this.outcomes,
    this.photoUrls = const [],
    this.status = EventReportStatus.generated,
    required this.generatedAt,
  });

  EventReport copyWith({EventReportStatus? status}) => EventReport(
    id: id,
    eventId: eventId,
    eventName: eventName,
    category: category,
    eventDate: eventDate,
    location: location,
    isOnline: isOnline,
    eventManagerName: eventManagerName,
    volunteerNames: volunteerNames,
    totalVolunteers: totalVolunteers,
    studentsReached: studentsReached,
    donationsCollected: donationsCollected,
    certificatesIssued: certificatesIssued,
    activityTitles: activityTitles,
    partnerDetails: partnerDetails,
    counsellorDetails: counsellorDetails,
    schoolFeedback: schoolFeedback,
    outcomes: outcomes,
    photoUrls: photoUrls,
    status: status ?? this.status,
    generatedAt: generatedAt,
  );
}

// ─── Daily Log Entry ──────────────────────────────────────────────────────────

class PipelineDailyLog {
  final int id;
  final String studentName;
  final int? eventId;
  final int? activityId;
  final String? eventTitle;
  final String? activityTitle;
  final DateTime date;
  final String title;
  final String content;
  final String? reflection;
  final List<String> photoUrls;
  final DateTime createdAt;

  const PipelineDailyLog({
    required this.id,
    required this.studentName,
    this.eventId,
    this.activityId,
    this.eventTitle,
    this.activityTitle,
    required this.date,
    required this.title,
    required this.content,
    this.reflection,
    this.photoUrls = const [],
    required this.createdAt,
  });
}

// ─── Pipeline Stats ───────────────────────────────────────────────────────────

class PipelineStats {
  final int totalEvents;
  final int activeEvents;
  final int pendingEmReviews;
  final int pendingAdminApprovals;
  final int certificatesToGenerate;
  final int impactDraftsPending;
  final int reportsPending;
  final int studentsReachedTotal;
  final double donationsTotal;

  const PipelineStats({
    this.totalEvents = 0,
    this.activeEvents = 0,
    this.pendingEmReviews = 0,
    this.pendingAdminApprovals = 0,
    this.certificatesToGenerate = 0,
    this.impactDraftsPending = 0,
    this.reportsPending = 0,
    this.studentsReachedTotal = 0,
    this.donationsTotal = 0,
  });

  static const empty = PipelineStats();
}
